### ISSUE TITLE
Can't Open Compressed Music XML Files

### ISSUE THREAD

**Issue by Menghini** [opensheetmusicdisplay/react-opensheetmusicdisplay#8]
This repository will load uncompressed Music XM files with ease, but does not load compressed music XML files. It would be nice if the code could load both types of files.

**Comment by sschmidTU** [comment]
You mean .mxl files? That's odd, because osmd.load() should handle that.
You could try to unzip it yourself and pass the xml content as string to OSMD.load().

**Comment by sschmidTU** [comment]
It works for me using an mxl file.

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/33069673/191064313-575bae26-2939-467b-95be-2e79e0463383.png">

If it still doesn't work for you, maybe you're using an old version of OSMD (if you did `npm install` a while ago)?
In that case, try deleting the node_modules/opensheetmusicdisplay folder and running `npm i` again.
You could check with `npm ls opensheetmusicdisplay` (should say 1.5.5 or greater)

**Comment by Menghini** [comment]
Is your mxl file a binary? I just attempted with a new repo and `npm install` and I still can't use a compressed mxl file. However, the uncompressed .xml files work just file. And to be clear, my compressed mxl file works just fine on the Public TypeScript Demo at https://opensheetmusicdisplay.org/demos/public-typescript-demo/.

The test files that I am using were made through MuseScore and can be found at https://drive.google.com/drive/folders/12vsH3hfArM0eMOWN6XVted6B47gGQKWV?usp=sharing. `Test.mxl` is a compressed binary file which the react version can't read and the `Test.musicxml` is the uncompressed file which the react version can read. The public typescript demo can read both files.

If I try to read the binary file I get a `opensheetmusicdisplay.min.js:31821 Uncaught (in promise) Error: Could not retrieve requested URL 0 at i.onreadystatechange (opensheetmusicdisplay.min.js:31821:1)` error in the console.

Edit: I just checked running `npm ls opensheetmusicdisplay` and my version is 1.5.5

**Comment by sschmidTU** [comment]
Your file is working for me, I don't know why it's not working for you.

<img width="781" alt="image" src="https://user-images.githubusercontent.com/33069673/191075358-eb7da1aa-1363-49a5-a599-2301f5028a12.png">

By the way, mxl is not a custom binary format, it's a zip of the musicxml file plus some info files. You can unzip it with zip programs.
![image](https://user-images.githubusercontent.com/33069673/191075718-27f6de87-0331-4884-958a-e5b95bb4acb4.png)

**Comment by sschmidTU** [comment]
Are you using MacOS? Which browser? Otherwise I don't know why it's not working the same for you.
All I did was checkout the repository, run npm install, add `<option value="Test.mxl">Test.mxl</option>` in App.js, add the .mxl file in the public/ folder, and run npm start.

**Comment by Menghini** [comment]
It appears that this is my error. I was referencing the file as `Test.xml` instead of `Test.mxl`. When referencing the file name by the correct file name, it works! Clearly I had a long night last night.. haha. You can consider this matter closed.

In other news, I have greatly enjoyed working with this library. I appreciate the great work you and your team have spent on this.
